Cria tela de lista de tarefas e tela de adicionar listas
angelicaameira/ListaDeTarefas pull request #8
Opened 2022-04-26 17:25 UTC by angelicaameira

Cria tela de lista de tarefas e tela de adicionar listas 
Cria relacionamento entre as classes no coredata

fixes #5 
fixes #6

2022-05-10 22:54 UTC, antoniogermano requested changes
Faça as alterações solicitadas

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaListaViewController.swift
> +			self.title = "Nova lista"
Corrija a indentação

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +        }else{
Corrija espaçamento

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +        if let tarefa = self.tarefaSelecionada{
Corrija espaçamento `nada{`

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +            } catch let erro  {
Corrija espaçamento `erro   {`

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +        else {
Corrija espaçamento e indentação `} else {`

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +            campoDescricao.text = ((tarefa.value(forKey: "descricao")) as! String)
Force unwrap dá crash no aplicativo, favor corrigir. Aproveite para usar guard let também e evitar o if hell

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        self.navigationItem.title = (listaSelecionada?.value(forKey: "descricao") as! String)
Force unwrap dá crash no app

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        let ordenacao = NSSortDescriptor(key: "descricao", ascending: true)
Fica mais organizado se você declarar as constantes primeiro e depois definir os valores na requisição

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +                self.listaDeTarefas = tarefasRecuperadas as! [NSManagedObject]
Force unwrap dá crash no app

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +                return
If hell, guard let

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        guard ((celula.textLabel?.text = (dadosTarefa.value(forKey: "descricao") as? String)) != nil) else { return celula }
Esse guard está bem desnecessariamente complicado, simplifique

2022-05-10 22:54 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        if tableView.cellForRow(at: indexPath)?.accessoryType == .disclosureIndicator {
Só pra constar, essa informação parece ser somente visual, não está sendo salva no CoreData. É esse o comportamento desejado?

2022-05-10 23:17 UTC, angelicaameira commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        if tableView.cellForRow(at: indexPath)?.accessoryType == .disclosureIndicator {
Nos próximos commits isso já foi corrigido e está salvando no CoreData

2022-05-11 00:08 UTC, antoniogermano requested changes
Faça as mudanças solicitadas

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +            return
if hell, guard let

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +            campoDetalhes.text = ((tarefa.value(forKey: "detalhes")) as? String)
A indentação está incorreta e a atribuição está desnecessariamente complicada, favor simplificar (parênteses desnecessários)

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        self.navigationItem.title = (listaSelecionada?.value(forKey: "descricao") as? String)
Parênteses desnecessários

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +                let tarefasRecuperadas = try contexto.fetch(requisicao)
Esse `let` acima do `guard let` é redundante/desnecessário

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +        guard let tarefa = self.tarefaSelecionada else { return }
Coloque o else em baixo do guard let

2022-05-11 00:08 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +            } catch let erro  {
Corrija espaçamento `erro  {`

2022-05-11 00:09 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +                let tarefasRecuperadas = try contexto.fetch(requisicao)
Corrija também a indentação

2022-05-11 22:06 UTC, antoniogermano requested changes

2022-05-11 22:06 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/AdicionaTarefaViewController.swift
> +        if let lista = listaSelecionada {
guard let

2022-05-11 22:06 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +            let tarefasRecuperadas = try contexto.fetch(requisicao) as? [NSManagedObject]
Corrija a indentação, os lets devem começar abaixo do guard e estar indentados no mesmo ponto.
```
guard
    let contexto = contexto,
    let tarefasRecuperadas = try contexto.fetch(requisicao) as? [NSManagedObject]
else { return }
```
Coloque uma linha em branco entre o else e o restante da função

2022-05-11 22:06 UTC, antoniogermano commented on ListaDeTarefas/ViewModel/ListaDeTarefasTableViewController.swift
> +        if let contexto = self.contexto{
guard let e espaçamento `o  {`

2022-05-13 11:16 UTC, antoniogermano approved these changes

2022-05-13 13:17 UTC, merged